"""initial schema

Revision ID: 1c717f354547
Revises: 
Create Date: 2025-10-10 18:04:21.438859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c717f354547'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_modelrun_market', 'model_runs', ['exchange', 'symbol', 'timeframe'], unique=False)
    op.create_index('ix_prices_market', 'prices', ['exchange', 'symbol', 'timeframe'], unique=False)
    op.create_index('ix_signal_created', 'signal_events', ['created_at'], unique=False)
    op.create_index('ix_signal_pairtf_dt', 'signal_events', ['exchange', 'symbol', 'timeframe', 'bar_dt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_pairtf_dt', table_name='signal_events')
    op.drop_index('ix_signal_created', table_name='signal_events')
    op.drop_index('ix_prices_market', table_name='prices')
    op.drop_index('ix_modelrun_market', table_name='model_runs')
    # ### end Alembic commands ###
